
services:
  s3-backup:
    build: .

    container_name: s3-backup

    restart: unless-stopped

    volumes:
      # Local PostgreSQL backups
      - /opt/test:/opt/test:rw

      # Configuration
      - ./config/config.yaml:/app/config/config.yaml:ro

    environment:
      TZ: Asia/Tehran

    mem_limit: 16m
    mem_reservation: 8m

    cpus: 0.50
    pids_limit: 100

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    networks:
      - backup-net

  minio:
    image: hub.hamdocker.ir/minio/minio:latest
    container_name: local-s3
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    networks:
      - backup-net

networks:
  backup-net: