backup:
  source_dir: - /opt/test
s3:
  endpoint_url: http://localhost:9000
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  bucket: "my-postgres-backups"
  prefix: "postgres/"
  region: "us-east-1"

retention:
  days: 10

logging:
  level: INFO

watcher:
  debounce_seconds: 5